BEGIN;

ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'CONFIGURING_PHOTOBOOK' BEFORE 'AWAITING_PAYMENT_PROOF';
ALTER TYPE custom_photobook_request_status ADD VALUE IF NOT EXISTS 'AWAITING_PAYMENT' BEFORE 'READY_FOR_PRODUCTION';

COMMIT;
